workaround for #455. Replacing git-remote-http and git-remote-https with older version from git 2.1.4

diff --git a/babun-core/plugins/pact/src/pact b/babun-core/plugins/pact/src/pact
--- a/babun-core/plugins/pact/src/pact
+++ b/babun-core/plugins/pact/src/pact
@@ -120,26 +120,6 @@ function checkpackages()
   fi
 }
 
-function checkPackagesCompatibility() {
-  for pkg in $packages
-    do      
-      if [[ $pkg == "git" ]]; then
-          if [[ force -eq 1 ]]; then
-             echo -e "CRITICAL: Installing git in force mode" 
-           else
-            echo -e "-------------------------------------------------------------------------------"
-            echo -e "CRITICAL: Git cannot be updated in this version!"
-            echo -e "Due to the bug https://github.com/babun/babun/issues/455 it's forbidden to install "
-            echo -e "git as it may not work correctly behind ntlm proxy"             
-            echo -e "If you know what you are doing add '--force' flag to proceed."
-            echo -e "-------------------------------------------------------------------------------"
-            exit 1
-          fi
-      fi
-    done
-}
-
-
 # process options
 noscripts=0
 invalidate=0
@@ -178,6 +158,24 @@ function checkCygwin() {
   fi
 }
 
+function checkPackageCompatibility() {
+  for pkg in $packages
+    do      
+      if [[ $pkg == "git" ]]; then
+          if [[ force -eq 1 ]]; then
+             echo -e "CRITICAL: Installing git in force mode..." 
+           else
+            echo -e "-------------------------------------------------------------------------------"
+            echo -e "CRITICAL: Git cannot be updated in this version!"
+            echo -e "Due to the bug https://github.com/babun/babun/issues/455 it's forbidden to install "
+            echo -e "git as it may not work correctly behind ntlm proxy."             
+            echo -e "If you know what you are doing add '--force' flag to proceed."
+            echo -e "-------------------------------------------------------------------------------"
+            exit 1
+          fi
+      fi
+    done
+}
 
 function installPkg()
 {
@@ -490,7 +488,7 @@ case "$command" in
   install)
     
     checkCygwin
-    checkPackagesCompatibility
+    checkPackageCompatibility
     checkpackages
     findworkspace
     getsetup
@@ -502,7 +500,7 @@ case "$command" in
   update)
     
     checkCygwin
-    checkPackagesCompatibility
+    checkPackageCompatibility
     removePkg
     checkpackages
     findworkspace
