Adding --force to pact. Disabling installation in case cygwin is outdated

diff --git a/babun-core/plugins/pact/src/pact b/babun-core/plugins/pact/src/pact
--- a/babun-core/plugins/pact/src/pact
+++ b/babun-core/plugins/pact/src/pact
@@ -27,27 +27,6 @@ if [ -z "$USER_AGENT" ]; then
 fi
   
 
-function checkCygwin() {
-  # Check if the underlying Cygwin distribution is up to date
-  local newest_cygwin_version=$( get_newest_cygwin_version )
-  if [[ -z "$newest_cygwin_version" ]]; then 
-    echo -e "[WARNING] Could not check the Cygwin distribution version. Installed packages may not work!"
-    return
-  else
-    local newest_cygwin_version_number=$( get_version_as_number $newest_cygwin_version )
-    local current_cygwin_version=$( get_current_cygwin_version )
-    local current_cygwin_version_number=$( get_version_as_number $current_cygwin_version )
-    if [[ $newest_cygwin_version_number -gt $current_cygwin_version_number ]]; then
-      echo -e "-------------------------------------------------------------------------------"
-      echo -e "WARNING: The underlying Cygwin kernel version is outdated!"
-      echo -e "It's forbidden to install new packages as they may fail to work." 
-      echo -e "Execute 'babun update' and follow the command-line instructions!"
-      echo -e "-------------------------------------------------------------------------------"
-      exit 1
-    fi    
-  fi
-}
-
 function usage()
 {
   echo pact: Installs and removes Cygwin packages.
@@ -64,6 +43,7 @@ function usage()
   echo "Options:"
   echo "  --mirror, -m <url> : set mirror"
   echo "  --invalidate, -i       : invalidates pact caches (setup.ini, etc.)"
+  echo "  --force, -f : force the execution"
   echo "  --help"
   echo "  --version"
 }
@@ -141,16 +121,40 @@ function checkpackages()
 }
 
 
-
-
 # process options
-
 noscripts=0
 invalidate=0
 file=""
 command=""
 filepackages=""
 packages=""
+force=0
+
+function checkCygwin() {
+  # Check if the underlying Cygwin distribution is up to date
+  local newest_cygwin_version=$( get_newest_cygwin_version )
+  if [[ -z "$newest_cygwin_version" ]]; then 
+    echo -e "[WARNING] Could not check the Cygwin distribution version. Installed packages may not work!"
+    return
+  else
+    local newest_cygwin_version_number=$( get_version_as_number $newest_cygwin_version )
+    local current_cygwin_version=$( get_current_cygwin_version )
+    local current_cygwin_version_number=$( get_version_as_number $current_cygwin_version )
+    if [[ $newest_cygwin_version_number -gt $current_cygwin_version_number ]]; then
+      if [[ force -eq 1 ]]; then
+          echo -e "CRITICAL: The underlying Cygwin version is outdated! Force option enabled - continuing!"
+      else 
+          echo -e "-------------------------------------------------------------------------------"
+          echo -e "CRITICAL: The underlying Cygwin version is outdated!"
+          echo -e "It's forbidden to install new packages as they may fail to work." 
+          echo -e "Execute 'babun update' and follow the instructions to update Cygwin."
+          echo -e "If you know what you are doing add '--force' flag to proceed."
+          echo -e "-------------------------------------------------------------------------------"
+          exit 1
+    fi    
+  fi
+}
+
 
 function installPkg()
 {
@@ -333,6 +337,11 @@ do
 
     --noscripts)
       noscripts=1
+      shift
+    ;;
+
+    --force|-f)
+      force=1
       shift
     ;;
 
