Fixing problems with file permissions on update

diff --git a/babun-core/plugins/core/src/babun b/babun-core/plugins/core/src/babun
--- a/babun-core/plugins/core/src/babun
+++ b/babun-core/plugins/core/src/babun
@@ -111,7 +111,7 @@ function update()
   if [ "$args" != "" ] && [ "$args" != "--force" ]; then echo "ERROR: Wrong argument $args"; exit 1; fi
   echo "Executing babun update"
 
-  permcheck=$( chmod 755 /usr/ 2> /dev/null || echo "FAILED" )
+  permcheck=$( chmod 777 /usr/ 2> /dev/null || echo "FAILED" )
   if [[  $permcheck == "FAILED" ]]; then
     echo -e "You don't have write permission to / filesystem. Aborting!"
     echo -e "Hint: Have you installed babun as admin and run it from a non-admin account? Retry as admin." 
